add delete course endpoint
TV3ntu/PDS-2024-backend pull request #136
Opened 2024-06-01 21:46 UTC by TV3ntu

2024-06-01 21:48 UTC, ilrosaunsam submitted a review, later dismissed

2024-06-01 23:22 UTC, ilrosaunsam approved these changes

2024-06-04 00:12 UTC, RafaelJoseCalderon requested changes
Rompe en "Principal"
 causa: FetchType.LAZY

Rompe en "DELETE api/course/{id}"
 causa: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violación de una restricción de Integridad Referencial: "FKDEPNI93SDOH2C2FPGHMC4YORM: PUBLIC.APP_ASSIGNMENT FOREIGN KEY(COURSE_ID) REFERENCES PUBLIC.APP_COURSE(ID) (UUID '952014fa-efd2-4149-b2ad-223e6a444b6e')"

Duda, como sabemos en el metodo create course a que institucin pertenece el curso?

2024-06-04 03:25 UTC, ilrosaunsam approved these changes

2024-06-04 14:26 UTC, RafaelJoseCalderon requested changes
Rompe en "Principal"
causa: FetchType.LAZY

Rompe en "DELETE api/course/{id}"
contexto:
   * borro un curso al cual nadie se inscribio, todo ok
   * me inscribo a un curso y luedo trato de borrar, <rompe>
     causa: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Violación de una
                 restricción de Integridad Referencial: "FKRNCO3GVOA5IJ9QLF07DLJKDST:
                 PUBLIC.USER_ASSIGNMENT FOREIGN KEY(ASSIGNMENT_ID)
                 REFERENCES PUBLIC.APP_ASSIGNMENT(ID) (UUID '011c1f76-9e3b-4d0f-af83-fa880188d36a')"

- Duda, como administramos a los usuarios que ya se incribieron a un curso? o sea, se incriben y las borro el curso que a su vez les borra los clases y... y entnces? 
- Duda, como sabemos en el metodo create course a que institucin pertenece el curso?

2024-06-04 14:32 UTC, merged