refactorizacion primer intento
TV3ntu/PDS-2024-backend pull request #81
Opened 2024-05-08 16:17 UTC by RafaelJoseCalderon

2024-05-08 23:06 UTC, ilrosaunsam requested changes

2024-05-08 23:06 UTC, ilrosaunsam commented on src/main/kotlin/ar/edu/unsam/pds/controllers/AssignmentController.kt
> +    @GetMapping(value = ["/"])
@GetMapping("/") asi en todos, como lo hablamos en la llamada

2024-05-09 00:24 UTC, fmnicotra12 approved these changes

2024-05-09 00:25 UTC, ilrosaunsam approved these changes

2024-05-09 00:28 UTC, merged