Feature/endpoint update user
TV3ntu/PDS-2024-backend pull request #86
Opened 2024-05-09 20:52 UTC by ilrosaunsam

detalle usuario:
![image](https://github.com/TV3ntu/PDS-2024-backend/assets/101224335/fc9c7fea-9940-4175-a288-f55e7bcf24ee)

modifica usuario:
![image](https://github.com/TV3ntu/PDS-2024-backend/assets/101224335/79bef258-35d9-481b-bf7a-252e3c90fd8d)

get trae usuario modificado:
![image](https://github.com/TV3ntu/PDS-2024-backend/assets/101224335/fafc8da7-9d4e-4231-a122-1cb49f64422f)

2024-05-09 22:32 UTC, fmnicotra12 commented on src/main/kotlin/ar/edu/unsam/pds/services/UserService.kt
> +    private fun buildUserDto(user: User): UserResponseDto {
Usar los mapper que estan en la clase Mapper que se creo, si no esta ese buildUserDto en la clase, creala ahi y usala desde ahi adentro

2024-05-09 22:32 UTC, fmnicotra12 commented on src/main/kotlin/ar/edu/unsam/pds/services/UserService.kt
> +        return UserDetailDto(
Meter dto en los mapper

2024-05-09 22:32 UTC, fmnicotra12 commented on src/main/kotlin/ar/edu/unsam/pds/services/UserService.kt
> +        return UserDetailDto(
Dto en mapper

2024-05-10 01:11 UTC, ilrosaunsam commented
perfecto ahi los pase al mapper los dto. tambien pase el de otros que estaban en los service si podes revisarlos mejor!

2024-05-10 01:48 UTC, RafaelJoseCalderon requested changes
en "package ar.edu.unsam.pds.controllers" el test "test get all the courses from an institution", se sugiere:
val courses = InstitutionCoursesResponseDto(
    mutableSetOf(Course("title 1", "description", "category", ""))
)

en "package ar.edu.unsam.pds.controllers" el test "test get all the assignments from an course", se sugiere:
val assignments = CourseAssignmentsResponseDto(
    mutableSetOf(Assignment(LocalTime.now(), LocalTime.now(), mutableListOf("Monday", "Wednesday"), 10, true, 100)
)
        )

2024-05-10 13:22 UTC, fmnicotra12 commented on src/main/kotlin/ar/edu/unsam/pds/dto/response/CourseResponseDto.kt
> +    val assignments : MutableSet<Assignment>
El dto no puede tener como atributo a una entidad, si es un dto tiene que tener como atributo a otro dto
Assignments: MutableSet<AssignmenDto>

Separar este dto en un archivo nuevo

Hace falta hacer un dto solo que tiene como atributo una lista de otros dto? capaz con poner que el metodo devuelva un List<AssignmentDto> es mas facil

2024-05-10 13:22 UTC, fmnicotra12 commented on src/main/kotlin/ar/edu/unsam/pds/dto/response/InstitutionResponseDto.kt
> +    val courses : MutableSet<Course>
Lo mismo que el comentario de arriba

2024-05-10 16:09 UTC, ilrosaunsam commented on src/main/kotlin/ar/edu/unsam/pds/dto/response/CourseResponseDto.kt
> +    val assignments : MutableSet<Assignment>
entiendo que aca decis que haga asi:
val assignments : List<AssignmentResponseDto> ?

o al al method getAssignmentOfCourse que sea del tipo lista?

2024-05-10 21:12 UTC, agusnarvaez submitted a review, later dismissed

2024-05-10 21:16 UTC, agusnarvaez approved these changes

2024-05-10 21:16 UTC, RafaelJoseCalderon approved these changes

2024-05-10 21:17 UTC, merged